# Generated by Django 4.2.2 on 2023-09-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroptions',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='useroptions',
            name='mobile_notifications',
        ),
        migrations.RemoveField(
            model_name='useroptions',
            name='mobile_number',
        ),
        migrations.DeleteModel(
            name='CountryCode',
        ),
    ]
