# Generated by Django 4.2.2 on 2023-10-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0003_todolist_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='access_granted',
        ),
        migrations.AddField(
            model_name='todolist',
            name='access_granted',
            field=models.BooleanField(default=False),
        ),
    ]
