# Generated by Django 4.2.2 on 2024-01-04 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list_app', '0004_remove_todolist_access_granted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroptions',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='owner',
        ),
        migrations.AddField(
            model_name='todolist',
            name='owner',
            field=models.ManyToManyField(blank=True, null=True, related_name='todo_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
