# Generated by Django 4.2.2 on 2024-01-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0006_todolist_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroptions',
            name='font_style',
            field=models.CharField(choices=[('1', 'Marck Script'), ('2', 'Dancing Script'), ('3', 'Indie Flower'), ('4', 'Pacifico'), ('5', 'Arial')], default='1', max_length=255),
        ),
    ]
