# Generated by Django 4.2.2 on 2024-01-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0007_useroptions_font_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroptions',
            name='font_style',
            field=models.CharField(choices=[('1', 'Marck Script'), ('2', 'Dancing Script'), ('3', 'Marcellus'), ('4', 'Roboto Slab'), ('5', 'Oswald')], default='1', max_length=255),
        ),
    ]
