# Generated by Django 4.2.6 on 2025-01-17 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list_app', '0008_alter_useroptions_font_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroptions',
            name='mode',
            field=models.CharField(choices=[('1', 'Light'), ('2', 'Dark'), ('3', 'Modern Code Editor'), ('4', 'Terminal')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='todo_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useroptions',
            name='font_style',
            field=models.CharField(choices=[('1', 'Marck Script'), ('2', 'Dancing Script'), ('3', 'Marcellus'), ('4', 'Roboto Slab'), ('5', 'Oswald'), ('6', 'Fixedsys Excelsior 3.01'), ('7', 'Arial'), ('8', 'Times New Roman'), ('9', 'Courier New'), ('10', 'Verdana'), ('11', 'Georgia'), ('12', 'Comic Sans MS'), ('13', 'Impact'), ('14', 'Lucida Console'), ('15', 'Tahoma'), ('16', 'Trebuchet MS'), ('17', 'Consolas'), ('18', 'Monaco'), ('19', 'Monospace')], default='1', max_length=255),
        ),
    ]
