# Generated by Django 4.2.6 on 2025-01-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0009_useroptions_mode_alter_todolist_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroptions',
            name='dark_mode',
        ),
    ]
